// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20211004112130_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.CarDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Discount = 12,
                            Model = "ModelX",
                            Price = 100000.0
                        },
                        new
                        {
                            Id = 20002,
                            Discount = 8,
                            Model = "ModelY",
                            Price = 145000.0
                        },
                        new
                        {
                            Id = 30003,
                            Discount = 14,
                            Model = "ModelZ",
                            Price = 243000.0
                        });
                });

            modelBuilder.Entity("Database.Models.DictionaryDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EngWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlWord")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dictionary");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            EngWord = "one",
                            PlWord = "jeden"
                        },
                        new
                        {
                            Id = 20002,
                            EngWord = "two",
                            PlWord = "dwa"
                        },
                        new
                        {
                            Id = 30003,
                            EngWord = "three",
                            PlWord = "trzy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
